server:
  port: 7777
spring:
  application:
    name: hello-world-provider
dubbo:
  application:
    name: hello-world-provider
  scan:
    base-packages: helloworld.service.impl
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20880